<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>Rediscovery.Feature.Client.FileExchange.UI</RootNamespace>
    <Authors>Christoph Taucher</Authors>
    <Version>0.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.12" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.12" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IPCPipe\IPCPipe.csproj" />
  </ItemGroup>
</Project>
