<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationAuthenticationProvider\CommunicationAuthenticationProvider.csproj" />
    <ProjectReference Include="..\CommunicationFeatureProvider\CommunicationFeatureProvider.csproj" />
    <ProjectReference Include="..\CommunicationResourceProvider\CommunicationResourceProvider.csproj" />
  </ItemGroup>

</Project>
