<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>Assets\rediscovery.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <Folder Include="Notifications\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.11" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.11" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RediscoveryManager.Service\RediscoveryManager.Service.csproj" />
  </ItemGroup>
</Project>
