<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>Assets\rediscovery.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.11" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="0.9.11" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.11" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RediscoveryManager.Service\RediscoveryManager.Service.csproj" />
    <ProjectReference Include="..\SharedConfigurations\SharedConfigurations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
