<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--<OutputType>Exe</OutputType>-->
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Remove="Devices\DevicesControl.xaml" />
    <AvaloniaResource Remove="Features\FeaturesControl.xaml" />
    <AvaloniaResource Remove="Features\Firewall\FirewallControl.xaml" />
    <AvaloniaResource Remove="Features\LiveLogger\LiveLoggerControl.xaml" />
    <AvaloniaResource Remove="IncomingConnection.xaml" />
    <AvaloniaResource Remove="Info\ServiceInfo.xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Devices\DevicesControl.xaml" />
    <None Remove="Features\FeaturesControl.xaml" />
    <None Remove="Features\Firewall\FirewallControl.xaml" />
    <None Remove="Features\LiveLogger\LiveLoggerControl.xaml" />
    <None Remove="IncomingConnection.xaml" />
    <None Remove="Info\ServiceInfo.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.1" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="NSubsys" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Connection\IncomingConnection.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IPCPipe\IPCPipe.csproj" />
    <ProjectReference Include="..\PluginFeature\PluginFeature.csproj" />
    <ProjectReference Include="..\SharedCommandArguments\SharedCommandArguments.csproj" />
    <ProjectReference Include="..\SharedConfigurations\SharedConfigurations.csproj" />
    <ProjectReference Include="..\SharedCoreModels\SharedCoreModels.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Connection\IncomingConnection.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Devices\DevicesControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Features\FeaturesControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Info\ServiceInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Features\LiveLogger\LiveLoggerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Features\Firewall\FirewallControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>
