<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationAuthenticationProvider\Rediscovery.Communication.Provider.Authentication.csproj" />
    <ProjectReference Include="..\Rediscovery.Client.Shared.Core\Rediscovery.Client.Shared.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\" />
  </ItemGroup>

</Project>
