<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationAuthenticationConsumer\Rediscovery.Communication.Consumer.Authentication.csproj" />
    <ProjectReference Include="..\CommunicationFeatureConsumer\Rediscovery.Communication.Consumer.Feature.csproj" />
    <ProjectReference Include="..\CommunicationHearthbeatConsumer\Rediscovery.Communication.Consumer.Heartbeat.csproj" />
    <ProjectReference Include="..\CommunicationLoggerConsumer\Rediscovery.Communication.Consumer.Logger.csproj" />
    <ProjectReference Include="..\Communication\Rediscovery.Communication.Consumer.Resource.csproj" />
    <ProjectReference Include="..\Rediscovery.Client.Shared.Core\Rediscovery.Client.Shared.Core.csproj" />
  </ItemGroup>

</Project>
