<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject>DesktopFeatureTestApp.ProgramConsole</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopFeatureConsole\DesktopFeatureConsole.csproj" />
  </ItemGroup>

</Project>
