<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject>DesktopFeatureTestApp.ProgramConsole</StartupObject>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <Version>0.0.0.1</Version>
    <Authors>Christoph Taucher</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/Chtau/Rediscovery</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Chtau/Rediscovery</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopFeatureConsole\Rediscovery.Feature.Desktop.Console.csproj" />
    <ProjectReference Include="..\DesktopFeatureMediaPlayer\Rediscovery.Feature.Desktop.MediaPlayer.csproj" />
    <ProjectReference Include="..\PluginFeature\PluginFeature.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
