<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon />
    <StartupObject>DesktopFeatureTestApp.ProgramConsole</StartupObject>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopFeatureConsole\DesktopFeatureConsole.csproj" />
    <ProjectReference Include="..\DesktopFeatureVLC\DesktopFeatureVLC.csproj" />
  </ItemGroup>

</Project>
