<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.29.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedCoreModels\SharedCoreModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Proto\authentication.proto" GrpcServices="Server" Link="Protos\authentication.proto" />
  </ItemGroup>

</Project>
