<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationAuthenticationConsumer\CommunicationAuthenticationConsumer.csproj" />
    <ProjectReference Include="..\CommunicationFeatureConsumer\CommunicationFeatureConsumer.csproj" />
    <ProjectReference Include="..\Communication\CommunicationResourceConsumer.csproj" />
  </ItemGroup>

</Project>
