#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Rediscovery.Client.App.MobileAndroid.Resource", IsApplication=true)]

namespace Rediscovery.Client.App.MobileAndroid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int background = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int green = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ic_launcher_background = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int light_grey = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int red = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int text_dark = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int text_light = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int theme_blue_accent = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int theme_blue_background = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int theme_blue_primary = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int theme_blue_primary_dark = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int theme_blue_text = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int theme_green_accent = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int theme_green_background = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int theme_green_primary = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int theme_green_primary_dark = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int theme_green_text = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int theme_purple_accent = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int theme_purple_background = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int theme_purple_primary = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int theme_purple_primary_dark = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int theme_purple_text = 2130771990;
			
			// aapt resource value: 0x7F01001C
			public const int theme_rediscovery_accent = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int theme_rediscovery_analogous_one = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int theme_rediscovery_analogous_two = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int theme_rediscovery_primary = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int theme_rediscovery_primary_dark = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int theme_rediscovery_primary_light = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int theme_rediscovery_primary_shade_black = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int theme_rediscovery_primary_shade_black_darkest = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int theme_rediscovery_primary_shade_white = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int theme_rediscovery_primary_shade_white_lightes = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int theme_rediscovery_triadic_one = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int theme_rediscovery_triadic_two = 2130772007;
			
			// aapt resource value: 0x7F010017
			public const int theme_red_accent = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int theme_red_background = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int theme_red_primary = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int theme_red_primary_dark = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int theme_red_text = 2130771995;
			
			// aapt resource value: 0x7F010028
			public const int theme_yellow_accent = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int theme_yellow_background = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public const int theme_yellow_primary = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public const int theme_yellow_primary_dark = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public const int theme_yellow_text = 2130772012;
			
			// aapt resource value: 0x7F01002D
			public const int touch_effect = 2130772013;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fab_margin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int nav_header_height = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int nav_header_vertical_spacing = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int spacing_double = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int spacing_huge = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int spacing_micro = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int spacing_normal = 2130837512;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030005
			public const int icon_devicefeature_default = 2130903045;
			
			// aapt resource value: 0x7F030001
			public const int ic_menu_devices = 2130903041;
			
			// aapt resource value: 0x7F030000
			public const int ic_menu_device_add = 2130903040;
			
			// aapt resource value: 0x7F030002
			public const int ic_menu_discovery = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_menu_features = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ic_menu_settings = 2130903044;
			
			// aapt resource value: 0x7F030006
			public const int ripple = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int selector_button = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int selector_checkable = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int selector_false = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int selector_true = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int side_nav_bar = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int splash_logo = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int splash_screen = 2130903053;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int action_settings = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int content_main_container = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int devicefeatures = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int drawer_layout = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int fab = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int feature_icon = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int feature_title = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int imageView = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int mask = 2130968584;
			
			// aapt resource value: 0x7F04000A
			public const int nav_devices = 2130968586;
			
			// aapt resource value: 0x7F040009
			public const int nav_device_add = 2130968585;
			
			// aapt resource value: 0x7F04000B
			public const int nav_discovery = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int nav_features = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int nav_settings = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int nav_view = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int textView = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int toolbar = 2130968592;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_bar_main = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int content_main = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int fragment_dashboard_devices = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int fragment_dashboard_features = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int fragment_discovery = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int item_devicefeature = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int nav_header_main = 2131034119;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main_drawer = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int menu_main = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int feature = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int navigation_drawer_close = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int navigation_drawer_open = 2131230724;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppThemeRediscovery_Splash = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int AppTheme_AppBarOverlay = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int AppTheme_PopupOverlay = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int Rediscovery = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int Rediscovery_Blue = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int Rediscovery_CompoundButton = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Rediscovery_CompoundButton_False = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Rediscovery_CompoundButton_Radio = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int Rediscovery_CompoundButton_True = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int Rediscovery_Green = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int Rediscovery_NoActionBar = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int Rediscovery_Purple = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int Rediscovery_Red = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int Rediscovery_TextAppearance = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int Rediscovery_TextAppearance_Subhead = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int Rediscovery_TextAppearance_Title = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int Rediscovery_TextAppearance_Title_Inverse = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int Rediscovery_TextAppearance_Title_Picker = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int Rediscovery_Yellow = 2131296274;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
