<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationAuthenticationConsumer\CommunicationAuthenticationConsumer.csproj" />
    <ProjectReference Include="..\CommunicationHearthbeatConsumer\CommunicationHeartbeatConsumer.csproj" />
    <ProjectReference Include="..\CommunicationLoggerConsumer\CommunicationLoggerConsumer.csproj" />
    <ProjectReference Include="..\Communication\CommunicationResourceConsumer.csproj" />
    <ProjectReference Include="..\SharedModels\SharedBase.csproj" />
  </ItemGroup>

</Project>
