syntax = "proto3";

import "shared.proto";

package featuredata;

service FeatureExchange {
  rpc ExchangeStream (stream DeviceFeatureData) returns (stream DeviceFeatureData);
  rpc ChangeFeatureState (FeatureState) returns (FeatureState);
  rpc FeatureClient (FeatureRequest) returns (FeatureClientData);
}

message FeatureState {
	string featureId = 1;
	enum State {
        Unknown = 0;
        Start = 1;
        Stop = 2;
        Error = 3;
    }
    State featureState = 2;
}

message DeviceFeatureData {
  string deviceId = 1;
  string featureId = 2;
  string profileId = 3;
  string data = 4;
}

message FeatureRequest {
    string featureId = 1;
}

message FeatureClientData {
    string featureId = 1;
    repeated byte archive = 2;
    FeatureDetailSetting setting = 2;
    repeated FeatureDetailProfile profiles = 3;
}