syntax = "proto3";

package handshake;

service HandShakeExchange {
  rpc Greeting (GreetingMessage) returns (GreetingReply);
}

message GreetingMessage {
  string deviceIdentifier = 1;
  string deviceName = 2;
  string model = 3;
  string manufacturer = 4;
  string oSVersion = 5;
  string platform = 6;
  string idiom = 7;
  string deviceType = 8;
}

message GreetingReply {
  int32 SSLPort = 1;
  string PEM = 2;
  enum State {
    None = 0;
    OK = 1;
    Error = 2;
    Denied = 3;
    WaitForApprovel = 4;
  }
  State CanConnect = 3;
}