syntax = "proto3";

package logger;

service LoggerExchange {
  rpc Add (stream LogEntry) returns (stream LogState);
  rpc LoggerCommand (LogCommandConfig) returns (LogCommandState);
}

message LogEntry {
   LoggerType loggerType = 1;
   string id = 2;
   string message = 3;
   string module = 4;
   uint64 time = 5;

  enum LoggerType {
    Trace = 0;
    Debug = 1;
    Information = 2;
    Warning = 3;
    Error = 4;
    Critical = 5;
  }
}

message LogState {
    bool ok = 1;
}

message LogCommandConfig {
    string id = 1;
    enum Command {
        Clear = 0;
        ChangeLogLevel = 1;
    }
    Command logCommand = 2;
    string data = 3;
}

message LogCommandState {
    string id = 1;
    bool ok = 2;
}