syntax = "proto3";

import "google/protobuf/empty.proto";
import "shared.proto";

package resources;

service ResourceExchange {
  rpc ActiveDevices (google.protobuf.Empty) returns (stream DeviceInfoList);
  rpc PendingDevices (google.protobuf.Empty) returns (stream DeviceInfoList);
  rpc Devices (google.protobuf.Empty) returns (stream DeviceInfoList);
  rpc UpdateDevice (DeviceInfo) returns (DeviceInfo);
  rpc DeleteDevice (DeviceChangeRequest) returns (DeviceChangeRequest);
  rpc ResolvePendingDevice (DevicePendingRequest) returns (DeviceChangeRequest);

  rpc Features (google.protobuf.Empty) returns (stream FeatureList);
  rpc FeatureDetail (FeatureDetailRequest) returns (FeatureDetails);

  rpc HeartbeatStatistic (google.protobuf.Empty) returns (stream HeartbeatStatisticList);
}

message DeviceInfoList {
    repeated DeviceInfo devices = 1;
}

message DeviceChangeRequest {
    string id = 1;
    ActionResult result = 2;
    enum ActionResult {
        None = 0;
        Ok = 1;
        Error = 2;
    }
}

message DevicePendingRequest {
    string id = 1;
    bool accept = 2;
}

message FeatureList {
    repeated FeatureDefinitionExtended features = 1;
}

message FeatureDetailRequest {
    string featureId = 1;
}

message FeatureDetails {
    string featureId = 1;
    FeatureDetailSetting setting = 2;
    repeated FeatureDetailProfile profiles = 3;
}

message HeartbeatStatisticList {
    repeated HeartbeatStatisticItem beats = 1;
}

message HeartbeatStatisticItem {
    string deviceId = 1;
    uint64 pingPongTime = 2;
    uint64 pingStartDatetimeUTC = 3;
    bool oK = 4;
    uint64 resultReceived = 5;
}