syntax = "proto3";

import "google/protobuf/empty.proto";
import "shared.proto";

package resources;

service ResourceExchange {
  rpc ActiveDevices (google.protobuf.Empty) returns (stream DeviceInfoList);
  rpc PendingDevices (google.protobuf.Empty) returns (stream DeviceInfoList);
  rpc Devices (google.protobuf.Empty) returns (stream DeviceInfoList);
  rpc UpdateDevice (DeviceInfo) returns (DeviceInfo);
  rpc DeleteDevice (DeviceChangeRequest) returns (DeviceChangeRequest);
  rpc ResolvePendingDevice (DevicePendingRequest) returns (DeviceChangeRequest);

  rpc Features (google.protobuf.Empty) returns (stream FeatureList);
  rpc FeatureDetail (FeatureDetailRequest) returns (FeatureDetails);
  rpc FeatureDetailProfileDelete (FeatureDetailProfileDeleteRequest) returns (FeatureDetailProfileDeleteRequest);
  rpc FeatureDetailProfileSave (FeatureDetailProfileSaveRequest) returns (FeatureDetailProfileSaveRequest);
  rpc FeatureDetailSettingSave (FeatureDetailSettingSaveRequest) returns (FeatureDetailSettingSaveRequest);
}

message DeviceInfoList {
    repeated DeviceInfo devices = 1;
}

message DeviceInfo {
    string id = 1;
    string identifier = 2;
    string name = 3;
    bool allowAccess = 4;
    uint64 requestTime = 5;
    string model = 6;
    string manufacturer = 7;
    string oSVersion = 8;
    string platform = 9;
    string idiom = 10;
    string deviceType = 11;
}

message DeviceChangeRequest {
    string id = 1;
    ActionResult result = 2;
    enum ActionResult {
        None = 0;
        Ok = 1;
        Error = 2;
    }
}

message DevicePendingRequest {
    string id = 1;
    bool accept = 2;
}

message FeatureList {
    repeated FeatureDefinitionExtended features = 1;
}

message FeatureDetailRequest {
    string featureId = 1;
}

message FeatureDetails {
    string featureId = 1;
    FeatureDetailSetting setting = 2;
    repeated FeatureDetailProfile profiles = 3;
    bytes settingUI = 4;
    bytes profileUI = 5;
}

message FeatureDetailProfileDeleteRequest {
    string featureId = 1;
    string profileId = 2;
    ActionResult result = 3;
    enum ActionResult {
        None = 0;
        Ok = 1;
        Error = 2;
    }
}

message FeatureDetailProfileSaveRequest {
    string featureId = 1;
    FeatureDetailProfile profile = 2;
    ActionResult result = 3;
    enum ActionResult {
        None = 0;
        Ok = 1;
        Error = 2;
    }
}

message FeatureDetailSettingSaveRequest {
    string featureId = 1;
    FeatureDetailSetting setting = 2;
    ActionResult result = 3;
    enum ActionResult {
        None = 0;
        Ok = 1;
        Error = 2;
    }
}