<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Version>0.0.0.1</Version>
    <Authors>Christoph Taucher</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/Chtau/Rediscovery</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Chtau/Rediscovery</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.30.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationBase\CommunicationBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Proto\featureexchange.proto" GrpcServices="Server" Link="Protos\featureexchange.proto" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  
</Project>
