<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\exchange.js" />
    <None Remove="Assets\index.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\exchange.js" />
    <EmbeddedResource Include="Assets\index.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="0.14.0" />
    <PackageReference Include="Forms.Controls.FlexButton" Version="0.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.0.0.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.6.292" />
    <PackageReference Include="Xamarin.Forms" Version="4.6.0.726" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginFeature\PluginFeature.csproj" />
    <ProjectReference Include="..\..\SharedCoreModels\SharedCoreModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\DesktopFeatures\FeaturePage\TerminalPage\TerminalFeaturePage.xaml.cs">
      <DependentUpon>TerminalFeaturePage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Controls\Terminal.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\Authentication\AuthenticationKey.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopConfiguration\DesktopConfigurationEditPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopConfiguration\DesktopConfigurationPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopConfiguration\DiscoveryDevicesPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopFeatures\DesktopFeaturesPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopFeatures\FeaturePage\FeatureView\FeatureView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopFeatures\FeaturePage\MediaPlayer\MediaPlayerFeaturePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\DesktopFeatures\FeaturePage\TerminalPage\TerminalFeaturePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Features\Settings\SettingPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PlatformInterfaces\" />
  </ItemGroup>
</Project>