<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Version>0.0.0.1</Version>
    <Authors>Christoph Taucher</Authors>
    <Company>Christoph Taucher</Company>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/Chtau/Rediscovery</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Chtau/Rediscovery</RepositoryUrl>
    <RootNamespace>Rediscovery.Feature.Client.FileExchange</RootNamespace>
    <AssemblyName>Rediscovery.Feature.Client.FileExchange</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPCPipe\IPCPipe.csproj" />
    <ProjectReference Include="..\PluginFeature\Rediscovery.Feature.Plugin.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
