<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <PackageId>Rediscovery.Client.Service.Discovery</PackageId>
    <Version>0.0.0.1</Version>
    <Authors>Christoph Taucher</Authors>
    <Product>Rediscovery.Client.Service.Discovery</Product>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/Chtau/Rediscovery</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Chtau/Rediscovery</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedConfigurations\SharedConfigurations.csproj" />
    <ProjectReference Include="..\SharedFeatureFunctions\SharedFeatureFunctions.csproj" />
    <ProjectReference Include="..\SharedModels\SharedBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
